#!/bin/bash
minargs=1
if [ $# != $minargs ]; then
    printf "Argument count must be $minargs, you provided $#\n"
    printf "Possible uses: \n\t $0 \"DD-MMM-YY HH:MM\" \n\t $0 \"MMM-DD-YY HH:MM\"\n\t $0 \"DD-MMM-YY\" \n\t $0 \"MMM-DD-YY\"\n"
    exit 1
fi

wrap() {
      eval "$@"
        SUM_EXIT=$(($SUM_EXIT+$?))
    }

function displaytime {
    local T=$1
    local D=$((T/60/60/24))
    local H=$((T/60/60%24))
    local M=$((T/60%60))
    local S=$((T%60))
    [[ $D > 0 ]] && printf '%dd ' $D
    [[ $H > 0 ]] && printf '%dh ' $H
    [[ $M > 0 ]] && printf '%dm ' $M
    [[ $D > 0 || $H > 0 || $M > 0 ]]
    printf '%ds\n' $S
}

wrap curdate="$(date -u -d @$(($(date --date="$1" +%s)-$(date +%s))) +"%s")"
wrap displaytime "$curdate"
exit $SUM_EXIT
